services:
  - type: web
    name: codats-backend
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: yarn install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
